// All user-facing labels (pt-BR). Keep UI text here so it is easy to change.
export const S = {
  appTitle: "Assistente de Sinistros",
  appSubtitle: "Respostas com fonte citada a partir das condições gerais, normativos e do banco de sinistros",
  newConversation: "Nova conversa",
  conversations: "Conversas",
  noConversations: "Nenhuma conversa ainda.",
  untitled: "Conversa sem título",
  deleteConversation: "Excluir",
  confirmDelete: "Excluir esta conversa e todo o histórico?",
  loadingHistory: "Carregando conversa…",
  historyError: "Não foi possível carregar o histórico.",
  emptyChat: "Faça uma pergunta sobre coberturas, prazos, franquias ou um sinistro específico.",
  composerPlaceholder: "Pergunte, por exemplo: qual é o limite da cobertura de vidros no Seguro Auto?",
  send: "Enviar",
  cancel: "Cancelar",
  retry: "Tentar novamente",
  retryDisabled: "Esta falha não pode ser repetida automaticamente",
  retryIn: (s: number) => `Tentar novamente em ${s}s`,
  stages: {
    retrieving: "Buscando nos documentos…",
    searching_documents: "Buscando mais trechos nos documentos…",
    querying_db: "Consultando o banco de sinistros…",
    generating: "Gerando resposta…",
    waiting: "Enviando pergunta…",
  } as Record<string, string>,
  slowHint: "Está demorando mais que o normal. Você pode cancelar e tentar novamente.",
  errorTitle: "Não foi possível obter a resposta",
  errorCode: (code: string) => `Código: ${code}`,
  reference: (id: string) => `ref. ${id}`,
  partialLabel: "Trecho recebido antes da falha:",
  refusalTitle: "Sem fonte disponível",
  refusalHint: "Reformule a pergunta ou especifique o produto (Auto, Residencial ou Empresarial) e o documento.",
  refusalPii: "Restrição de privacidade",
  refusalProvider: "Pergunta recusada pelo provedor",
  sourcesChecked: "Fontes consultadas:",
  noSourcesChecked: "Nenhuma fonte relevante encontrada.",
  cancelledTitle: "Resposta interrompida pelo usuário",
  interruptedTitle: "Resposta interrompida",
  interruptedReasons: {
    stall: "A conexão ficou sem resposta.",
    network: "A conexão com o servidor foi perdida.",
    stream_ended: "A transmissão terminou antes da resposta completa.",
    SERVER_RESTART: "O serviço foi reiniciado durante a geração.",
  } as Record<string, string>,
  pendingTitle: "Resposta em andamento em outra sessão…",
  citations: "Fontes",
  citationVersion: (v: string) => `versão ${v}`,
  citationEffective: (d: string) => `vigente desde ${d}`,
  superseded: "versão superada",
  supersededHint: "Este documento foi substituído por uma versão mais recente.",
  databaseSource: "Banco de sinistros",
  rows: (n: number) => `${n} linha(s)`,
  readOnlyQuery: "consulta somente leitura",
  page: (p: number) => `p. ${p}`,
  provenance: {
    documents: (n: number) => (n === 1 ? "1 documento" : `${n} documentos`),
    database: "1 consulta ao banco",
    index: (d: string) => `Índice: ${d}`,
    snapshot: (d: string) => `Banco: ${d}`,
    latency: (ms: number) => `${(ms / 1000).toFixed(1).replace(".", ",")} s`,
    cost: (usd: number) => `US$ ${usd.toFixed(4).replace(".", ",")} (equivalente)`,
    tokens: (n: number) => `${n} tokens`,
  },
  banner: {
    open: "Assistente indisponível no momento: o provedor de IA não está respondendo. O histórico continua disponível; novas perguntas podem falhar.",
    rateLimited: "O provedor de IA atingiu o limite de uso. Novas perguntas podem falhar por alguns instantes.",
    halfOpen: "Reconectando ao provedor de IA…",
    unconfigured: "O provedor de IA não está configurado (chave ausente). Perguntas serão recusadas até a configuração.",
    apiDown: "Servidor indisponível. Verifique se a API está em execução.",
    checked: (s: number) => `verificado há ${s}s`,
  },
  errorFallback: {
    LLM_TIMEOUT: "O assistente não respondeu dentro do tempo limite.",
    LLM_RATE_LIMITED: "O provedor de IA atingiu o limite de uso. Aguarde e tente novamente.",
    LLM_UNAVAILABLE: "O assistente está temporariamente indisponível.",
    LLM_BAD_RESPONSE: "O assistente retornou uma resposta inválida.",
    LLM_MISCONFIGURED: "O assistente não está configurado corretamente. Contate o administrador.",
    BUDGET_EXCEEDED: "A pergunta excedeu o limite de processamento por consulta.",
    RESPONSE_TRUNCATED: "A resposta foi interrompida por exceder o tamanho máximo.",
    CANCELLED: "Resposta cancelada pelo usuário.",
    NETWORK: "Falha de rede ao contatar o servidor.",
    INTERNAL: "Ocorreu um erro interno. Tente novamente.",
  } as Record<string, string>,
};
